name: Generate and Publish Protobuf Files

on:
  pull_request:
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Buf
        uses: bufbuild/buf-action@v1
        with:
          lint: true
          format: true
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install protoc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
      - name: Regenerate .pb.go files
        run: |
          rm -rf ./gen
          buf generate
      - name: Update .proto files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ./gen
          git commit -m "Update generated .proto files" || echo "No changes to commit"
          git push