name: Generate and Publish Protobuf Files

on:
  pull_request:
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Buf
        uses: bufbuild/buf-action@v1
      - name: Lint proto files
        run: buf lint --error-format github-actions