name: Generate and Publish Protobuf Files

on:
  pull_request:
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Buf
        uses: bufbuild/buf-action@v1
        with:
          lint: true
      - name: Install protoc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
      - name: Format .proto files
        run: |
          buf format -w
      - name: Generate pb.go files
        run: |
          rm -rf ./gen
          buf generate
      - name: Update .proto files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add proto
          git commit -m "Apply Buf format changes" || echo "No changes to commit"
          git push origin ${{ github.ref_name }}