name: Generate and Publish Protobuf Files

on:
  pull_request:
    paths: ['proto/**']
  push:
    paths: ['proto/**']

permissions:
  contents: read
  pull-requests: write

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          lint: true
          format: true